### ISSUE TITLE
Plugin is not compatible with latest IntelliJ 2023.2

### ISSUE THREAD

**Issue by piskov** [nabato/alabaster-themes#2]
Plugin cannot be found via plugin search for 2023.2 release. If installed manually from disk, complains about the build:

<img width="486" alt="Screenshot 2023-08-25 at 18 58 13" src="https://github.com/vlnabatov/alabaster-themes/assets/4349021/f289378f-530f-4c1c-98e1-8ae6e0eecb89">

**Comment by nabato** [comment]
Should be fixed now. Sorry for such a long waiting.

**Comment by piskov** [comment]
Thank you, you’re the best :-)
