### ISSUE TITLE
Plugin is not compatible with latest IntelliJ 2023.3.1

### ISSUE THREAD

**Issue by olimsaidov** [nabato/alabaster-themes#5]
Plugin is not compatible with latest IntelliJ 2023.3.1

**Comment by kytta** [comment]
Why was this closed? I don't see any new version on GH, and JB Marketplace still marks it as incompatible...

**Comment by nabato** [comment]
@kytta, Intellij versioning is horrible and I messed up it. The fix will be available in a couple of day. Sorry for incovinience.
