### ISSUE TITLE
The Javascript function highlighting fix doesn't work

### ISSUE THREAD

**Issue by denblackstache** [nabato/alabaster-themes#6]
Hi. I've tried the theme in RubyMine 2023.3.4, WebStorm 2022.3.4, GoLand 2022.3.4, no luck. Both JS function declaration and function calls are not colored.

Should the theme's color scheme be set up in a specific way for this to work?

**Comment by nabato** [comment]
Jetbrains products are the worst. I'll take a look at it.

**Comment by nabato** [comment]
#3

**Comment by nabato** [comment]
[v1.0.82](https://github.com/nabato/alabaster-themes/releases/tag/v1.0.82)

**Comment by denblackstache** [comment]
@nabato, works great. Thanks!
