### ISSUE TITLE
Alabaster theme with Inspection Lens plugin styling issues

### ISSUE THREAD

**Issue by SimY4** [nabato/alabaster-themes#8]
# Given
Alabaster Theme plugin enabled
Inspection Lens plugin enabled

# When
Inspection Lens have something to add inline

# Expected
Alabaster theme highlighting is not affected. 

# Actual
Alabaster theme styles goes away for that line. See screenshot for example:

<img width="1023" alt="Screenshot 2024-05-03 at 11 08 38" src="https://github.com/nabato/alabaster-themes/assets/1394639/84c40289-8969-4978-a41a-20101882a863">

**Comment by nabato** [comment]
@SimY4, thank you bringing this issue. That's my results:

![Inspection Lens example](https://github.com/nabato/alabaster-themes/assets/8669892/62ff91d1-c29e-4e99-b770-463c41dab401).

Seems to work correctly. Can you please bring more context? Maybe a gif with explanation would be helpful.

**Comment by SimY4** [comment]
Still something that happens to me. I.e. (this is Scala BTW, not sure if syntax play role here).

<img width="392" alt="Screenshot 2024-05-06 at 10 20 12" src="https://github.com/nabato/alabaster-themes/assets/1394639/b63397ff-effc-4965-a89c-8be5985505bd">
<img width="379" alt="Screenshot 2024-05-06 at 10 20 23" src="https://github.com/nabato/alabaster-themes/assets/1394639/728d6cc3-b6dc-45bf-b75e-41a60e94bc5c">

UPD: Seems like it doesn't happen to method name highlighting. Mostly I see affecting string constants highlighting.

**Comment by nabato** [comment]
Improved string highlighting and added better Scala support in [v1.0.83](https://github.com/nabato/alabaster-themes/releases/tag/v1.0.83).

IDE breakpoints' correct behavior (fyi quotation marks is transparent):
![IDE breakpoint correct behavior](https://github.com/nabato/alabaster-themes/assets/8669892/47c6ccd6-e966-45a4-8901-97a8ad08a0b8)

Inspection Lens plugin incorrect behavior:
![Inspection Lens incorrect behavior](https://github.com/nabato/alabaster-themes/assets/8669892/bd779d5a-0e83-4ea3-ae82-21a7c2becf3e)

It seems Inspection Lens need to fix its behavior.

P.S. I'll plan in the future to change colored elements behavior when highlighted in BG theme, e.g. a green background string will change background to a blend of green and red when the line is breakpointed.
